workflows:
  cordova_android_build:
    name: Cordova Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      vars:
        CORDOVA_PLATFORM: "android"
        ANDROID_HOME: /opt/android-sdk
        PATH: $PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Accept Android Licenses
        working-directory: /opt/android-sdk
        run: |
          yes | ./cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install dependencies
        run: npm install

      - name: Add Android platform
        run: cordova platform add android

      - name: Build APK
        run: cordova build android --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: platforms/android/app/build/outputs/**/*.apk
